version: '3.8'

services:
  api:
    # Replace olamilekan2580 with your exact GitHub username in lowercase if different
    image: ghcr.io/olamilekan2580/devops-demo:latest
    container_name: secured-portfolio-api
    ports:
      - "8080:80"
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
